# AI Town Board Prep System Configuration

document_processing:
  docling:
    ocr_enabled: true
    table_extraction: true
    image_processing: true
    output_format: "markdown"
    batch_size: 5
    
agents:
  town_attorney:
    enabled: true
    llm_provider: "openai"  # or "anthropic"
    model: "gpt-4"
    temperature: 0.1
    max_tokens: 2000
    
storage:
  data_directory: "./data"
  backup_enabled: true
  retention_policy: "2_years"
  
logging:
  level: "INFO"
  file: "logs/ai_town_board.log"
  max_size_mb: 50
  backup_count: 5