# AI Town Board Prep System Configuration

document_processing:
  docling:
    ocr_enabled: true
    table_extraction: true
    image_processing: true
    output_format: "markdown"
    batch_size: 5
    
agents:
  town_attorney:
    enabled: true
    llm_provider: "openai"  # or "anthropic"
    model: "gpt-5"
    temperature: 0.1
    max_tokens: 2000
    api_key_env: "OPENAI_API_KEY"  # Environment variable name for API key
    
  # Alternative Anthropic configuration
  # town_attorney:
  #   enabled: true
  #   llm_provider: "anthropic"
  #   model: "claude-3-sonnet-20240229"
  #   temperature: 0.1
  #   max_tokens: 2000
  #   api_key_env: "ANTHROPIC_API_KEY"

# API Configuration - Uses your subscription via environment variables
api:
  openai:
    api_key_env: "OPENAI_API_KEY"  # Set this environment variable with your OpenAI API key
    base_url: null  # Use default OpenAI endpoint
    organization: null  # Optional: your OpenAI organization ID
    
  anthropic:
    api_key_env: "ANTHROPIC_API_KEY"  # Set this environment variable with your Anthropic API key
    base_url: null  # Use default Anthropic endpoint
    
storage:
  data_directory: "./data"
  backup_enabled: true
  retention_policy: "2_years"
  
logging:
  level: "INFO"
  file: "logs/ai_town_board.log"
  max_size_mb: 50
  backup_count: 5